/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics' // 'tutorial-basics'   'tutorial-extras'
    },
  ],

  js: [
    {
      type: 'autogenerated',
      dirName: 'js'
    }
  ],
  react: [
    {
      type: 'autogenerated',
      dirName: 'react'
    }
  ],
  vue: [
    {
      type: 'autogenerated',
      dirName: 'vue'
    }
  ],
  css: [
    {
      type: 'autogenerated',
      dirName: 'css'
    }
  ],
  leetcode: [
    {
      type: 'autogenerated',
      dirName: 'leetcode'
    }
  ]

};

module.exports = sidebars;
